### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by dutzi** [xigh/spectrogram#2]
Hey, I'm new to Go and having some difficulties compiling the project.

When running 

```sh
go build ./main.go
```

I get the following message:

```
main.go:11:2: no required module provides package github.com/xigh/go-wavreader: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Please help :)

**Comment by enoy19** [comment]
```
go build
```

without the `./main.go` did the trick for me

**Comment by xigh** [comment]
Yes, thank you @enoy19  ... go build is enough. Sorry @dutzi ... I did not see your message earlier.
